[package]
name = "rust_by_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "chapter1_1"
path = "src/chapter1_1.rs"

[[bin]]
name = "chapter1_2"
path = "src/chapter1_2.rs"